### ISSUE TITLE
Documentation update list

### ISSUE THREAD

**Issue by smeech** [espanso/espanso#1788]
A few items I have spotted. By no means exclusive!

ToDo:

- [ ] Privacy Policy #1560 [security.md](https://github.com/espanso/espanso/security) is due for an update
- [ ] Available match options https://github.com/espanso/website/issues/10 - all these are now present in the documentation in appropriate sections - I'm not sure a separate list would be useful?
- [ ] Usage of `use_standard_includes`?

Done:
- [x] Usage of `search_terms:`
- [x] Other options listed [here](https://github.com/espanso/espanso/blob/dfd695b8e0173d0c8c71e17714c6074cf641b7bd/espanso-config/src/config/parse/yaml.rs#L116): `x11_use_xdotool_backend`, `emulate_alt_codes`, `post_search_delay`, `post_form_delay`.
- [x] `emulate_alt_codes: true` [see here](https://github.com/espanso/espanso/releases/tag/v2.1.6-beta)
- [x] `filter_os:` rule
- [x] Autofix in the documentation seems to be outdated #1767
- [x] Update links to federico-terzi/espanso to espanso/espanso?
- [x] MacOS brew installation docs should be updated #1804
- [x] ?add Discord server to the docs header
- [x] Plain scalar Regex triggers are easier to debug if we don't have to escape every “\\”. I'll add a note about this.
- [x] `force_mode: clipboard|keys` and `force_clipboard: true` (possible duplicate of the first) #1690 Are there other undocumented controls? (See [parse.rs](https://github.com/espanso/espanso/blob/3f6444c8b5c0004287b9deb6b6a1aa414b1a36e4/espanso-config/src/matches/group/loader/yaml/parse.rs#L107).)
- [x] `left_word:` ord `right_word:` controls. See [here](https://discord.com/channels/884163483409731584/1013902234469269554/1200012576784916550).
- [x] Document markdown & html #1806
- [x] `paragraph:` prevents `markdown:` starting a new paragraph. See [here](https://discord.com/channels/884163483409731584/1013902234469269554/1199982192319803432).
- [x] Factors determining size of forms - [Discord conversation] (https://discord.com/channels/884163483409731584/1013916990760554608/1185019971185692682) & [Reddit] (https://www.reddit.com/r/espanso/comments/18ibpbi/help_with_making_forms_better/) summary
- [x] Output of UTF8 foreign characters (in Windows?) #1736 #1749 #1698
- [x] Ability to output Unicode characters, e.g. `replace: "\u0105"` (UTF-16), or `"\U00000105"` (UTF-32) or `"\xC4"` (UTF-8?)
- [x] Multiple filters, need to apply alphabetically by filename to determine application order #1269
- [x] CTRL-character triggers are possible but likely to cause problems in editors, and over-delete characters on triggering #383

**Comment by kpym** [comment]
> * [ ]  Output of UTF8 foreign characters in Windows [Espanso does not support UTF-8 return values from PowerShell #1736](https://github.com/espanso/espanso/issues/1736) [Problem with encoding Polish characters in shell #1749](https://github.com/espanso/espanso/issues/1749)

You may also want to mention #1698. This is not just Windows specific, I think. If you are using a script (e.g. Python) that produces output that is not UTF-8, there may be a problem.

For example, the documentation should probably have a "UTF-8" section with "Windows/PowerShell" and "Python/Other Scripts" as subsections.

**Comment by smeech** [comment]
> > * [ ]   Output of UTF8 foreign characters in Windows [Espanso does not support UTF-8 return values from PowerShell #1736](https://github.com/espanso/espanso/issues/1736) [Problem with encoding Polish characters in shell #1749](https://github.com/espanso/espanso/issues/1749)
> 
> You may also want to mention #1698. This is not just Windows specific, I think. If you are using a script (e.g. Python) that produces output that is not UTF-8, there may be a problem.

I've only encountered this being reported for Windows. I'm happy to amend the entry(ies) if it's occurring elsewhere.
> 
> For example, the documentation should probably have a "UTF-8" section with "Windows/PowerShell" and "Python/Other Scripts" as subsections.

It crops up in both the pre-existng **Shell** and **Script** sections so I'll probably make two entries, one in each.

**Comment by smeech** [comment]
Moved to espanso/website Issue [#38](https://github.com/espanso/website/issues/38).
